<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>


    <ItemGroup>
        <!-- Project References -->
        <ProjectReference Include="..\Warehouse.Domain\Warehouse.Domain.csproj" />
        <ProjectReference Include="..\Warehouse.Application\Warehouse.Application.csproj" />
    </ItemGroup>


    <ItemGroup>
        <!-- Firebase -->
        <PackageReference Include="FirebaseAdmin" Version="3.6.0" />
        <PackageReference Include="Google.Apis.Auth" Version="1.75.0" />


        <!-- Database -->
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.10" />

        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.0" />


        <!-- MinIO -->
        <PackageReference Include="Minio" Version="7.0.0" />

    </ItemGroup>


    <ItemGroup>
        <None Update="Firebase\serviceAccount.json">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>


</Project>