<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Warehouse.Domain\Warehouse.Domain.csproj" />
      <ProjectReference Include="..\Warehouse.Infrastructure\Warehouse.Infrastructure.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTOs\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="MediatR" Version="14.2.0" />
      <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.11" />
    </ItemGroup>

</Project>
