//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warehouse.Presentation.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Warehouse.Presentation.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard data retrieved successfully.
        /// </summary>
        public static string DashboardRetrieved {
            get {
                return ResourceManager.GetString("DashboardRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DTO was not found.
        /// </summary>
        public static string DtoNotFound {
            get {
                return ResourceManager.GetString("DtoNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product created.
        /// </summary>
        public static string ProductCreated {
            get {
                return ResourceManager.GetString("ProductCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description is required.
        /// </summary>
        public static string ProductDescriptionRequired {
            get {
                return ResourceManager.GetString("ProductDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expiry date must be in the future.
        /// </summary>
        public static string ProductExpiryDateMustBeFuture {
            get {
                return ResourceManager.GetString("ProductExpiryDateMustBeFuture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name cannot exceed {MaxLength} characters.
        /// </summary>
        public static string ProductNameMaxLength {
            get {
                return ResourceManager.GetString("ProductNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product name is required.
        /// </summary>
        public static string ProductNameRequired {
            get {
                return ResourceManager.GetString("ProductNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product not found.
        /// </summary>
        public static string ProductNotFound {
            get {
                return ResourceManager.GetString("ProductNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price must be greater than zero.
        /// </summary>
        public static string ProductPriceMustBePositive {
            get {
                return ResourceManager.GetString("ProductPriceMustBePositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity cannot be negative.
        /// </summary>
        public static string ProductQuantityCannotBeNegative {
            get {
                return ResourceManager.GetString("ProductQuantityCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity change cannot be zero..
        /// </summary>
        public static string QuantityChangeCannotBeZero {
            get {
                return ResourceManager.GetString("QuantityChangeCannotBeZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason is required..
        /// </summary>
        public static string ReasonRequired {
            get {
                return ResourceManager.GetString("ReasonRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU cannot exceed {MaxLength} characters.
        /// </summary>
        public static string SkuMaxLength {
            get {
                return ResourceManager.GetString("SkuMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SKU is required.
        /// </summary>
        public static string SkuRequired {
            get {
                return ResourceManager.GetString("SkuRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock adjustment created successfully.
        /// </summary>
        public static string StockAdjustmentCreated {
            get {
                return ResourceManager.GetString("StockAdjustmentCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier country cannot exceed {MaxLength} characters.
        /// </summary>
        public static string SupplierCountryMaxLength {
            get {
                return ResourceManager.GetString("SupplierCountryMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier country is required.
        /// </summary>
        public static string SupplierCountryRequired {
            get {
                return ResourceManager.GetString("SupplierCountryRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier created.
        /// </summary>
        public static string SupplierCreated {
            get {
                return ResourceManager.GetString("SupplierCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier deactivated successfully.
        /// </summary>
        public static string SupplierDeactivated {
            get {
                return ResourceManager.GetString("SupplierDeactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier email format is invalid.
        /// </summary>
        public static string SupplierEmailInvalid {
            get {
                return ResourceManager.GetString("SupplierEmailInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier email is required.
        /// </summary>
        public static string SupplierEmailRequired {
            get {
                return ResourceManager.GetString("SupplierEmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier name cannot exceed {MaxLength} characters.
        /// </summary>
        public static string SupplierNameMaxLength {
            get {
                return ResourceManager.GetString("SupplierNameMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier name is required.
        /// </summary>
        public static string SupplierNameRequired {
            get {
                return ResourceManager.GetString("SupplierNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier not found.
        /// </summary>
        public static string SupplierNotFound {
            get {
                return ResourceManager.GetString("SupplierNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier phone number cannot exceed {MaxLength} characters.
        /// </summary>
        public static string SupplierPhoneMaxLength {
            get {
                return ResourceManager.GetString("SupplierPhoneMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supplier phone number is required.
        /// </summary>
        public static string SupplierPhoneRequired {
            get {
                return ResourceManager.GetString("SupplierPhoneRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suppliers retrieved successfully.
        /// </summary>
        public static string SuppliersRetrieved {
            get {
                return ResourceManager.GetString("SuppliersRetrieved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation metadata retrieved successfully.
        /// </summary>
        public static string ValidationMetadataRetrieved {
            get {
                return ResourceManager.GetString("ValidationMetadataRetrieved", resourceCulture);
            }
        }
    }
}
